/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sj3ll75jcCl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function Marketplace() {
  return (
    <div className="bg-background">
      <header className="bg-muted/40 py-2 px-4 md:px-6 bg-gray-950 text-white">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <LeafIcon className="h-6 w-6 text-primary text-[#27925b]" />
            <span className="font-semibold text-lg text-[#27925b]">Agriconnect</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link href="#" className="gap-2 rounded-full px-4 py-2 font-medium transition-colors hover:bg-gray-100 dark:hover:bg-[#003B36]" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="gap-2 rounded-full px-4 py-2 font-medium transition-colors hover:bg-gray-100 dark:hover:bg-[#003B36]" prefetch={false}>
              Marketplace
            </Link>
            <Link href="#" className="gap-2 rounded-full px-4 py-2 font-medium transition-colors hover:bg-gray-100 dark:hover:bg-[#003B36]" prefetch={false}>
              Crop Monitoring
            </Link>
          </nav>
          <Button variant="outline" className="hidden md:inline-flex">
            Contact Us
          </Button>
        </div>
      </header>
      <section className="relative w-full h-[400px] md:h-[500px] lg:h-[600px] overflow-hidden">
        <img
          src="/bg.jpg"
          alt="Farmer's Market"
          width={1920}
          height={1080}
          className="w-full h-full object-cover"
          style={{ aspectRatio: "1920/1080", objectFit: "cover" }}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-background to-transparent" />
        <div className="absolute inset-0 flex flex-col items-center justify-center px-4 text-center">
          <h1 className="text-3xl md:text-5xl lg:text-6xl font-bold text-white mb-[5vw]">
            Discover Fresh Produce from Local Farmers
          </h1>
         
          <div className="max-w-xl w-full">
            <Input
              type="search"
              placeholder="Search local farm products..."
              className="w-full rounded-full bg-background px-6 py-3 text-primary-foreground shadow-lg focus:outline-none focus:ring-2 focus:ring-primary"
            />
          </div>
        </div>
      </section>
      <div className="container mx-auto grid grid-cols-1 md:grid-cols-[240px_1fr] gap-8 py-12 px-4 md:px-0">
        <div className="bg-muted rounded-lg p-6">
          <h2 className="text-xl font-bold mb-4">Categories</h2>
          <div className="grid gap-2">
            <Link href="#" className="text-primary-foreground hover:underline" prefetch={false}>
              Fruits
            </Link>
            <Link href="#" className="text-primary-foreground hover:underline" prefetch={false}>
              Vegetables
            </Link>
            <Link href="#" className="text-primary-foreground hover:underline" prefetch={false}>
              Grains
            </Link>
            <Link href="#" className="text-primary-foreground hover:underline" prefetch={false}>
              Herbs &amp; Spices
            </Link>
            <Link href="#" className="text-primary-foreground hover:underline" prefetch={false}>
              Nuts &amp; Seeds
            </Link>
            <Link href="#" className="text-primary-foreground hover:underline" prefetch={false}>
              Dairy
            </Link>
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          <div className="bg-muted rounded-lg overflow-hidden shadow-lg">
            <img
              src="/placeholder.svg"
              alt="Farmer's Apples"
              width={400}
              height={300}
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "400/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-bold mb-2">Fresh Apples from Farmer John</h3>
              <div className="flex items-center mb-2">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <span className="ml-2 text-muted-foreground">4.3</span>
              </div>
              <p className="text-muted-foreground mb-4">₹199 per kg</p>
              <Button className="w-full">Add to Cart</Button>
            </div>
          </div>
          <div className="bg-muted rounded-lg overflow-hidden shadow-lg">
            <img
              src="/placeholder.svg"
              alt="Organic Carrots from Farmer's Market"
              width={400}
              height={300}
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "400/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-bold mb-2">Organic Carrots from Farmer's Market</h3>
              <div className="flex items-center mb-2">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <span className="ml-2 text-muted-foreground">4.8</span>
              </div>
              <p className="text-muted-foreground mb-4">₹119 per kg</p>
              <Button className="w-full">Add to Cart</Button>
            </div>
          </div>
          <div className="bg-muted rounded-lg overflow-hidden shadow-lg">
            <img
              src="/placeholder.svg"
              alt="Whole Wheat Flour from Local Mill"
              width={400}
              height={300}
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "400/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-bold mb-2">Whole Wheat Flour from Local Mill</h3>
              <div className="flex items-center mb-2">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <span className="ml-2 text-muted-foreground">3.7</span>
              </div>
              <p className="text-muted-foreground mb-4">₹229 per kg</p>
              <Button className="w-full">Add to Cart</Button>
            </div>
          </div>
          <div className="bg-muted rounded-lg overflow-hidden shadow-lg">
            <img
              src="/placeholder.svg"
              alt="Fresh Basil from Farmer's Garden"
              width={400}
              height={300}
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "400/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-bold mb-2">Fresh Basil from Farmer's Garden</h3>
              <div className="flex items-center mb-2">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <span className="ml-2 text-muted-foreground">4.7</span>
              </div>
              <p className="text-muted-foreground mb-4">₹329 per bunch</p>
              <Button className="w-full">Add to Cart</Button>
            </div>
          </div>
          <div className="bg-muted rounded-lg overflow-hidden shadow-lg">
            <img
              src="/placeholder.svg"
              alt="Roasted Almonds from Local Farm"
              width={400}
              height={300}
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "400/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-bold mb-2">Roasted Almonds from Local Farm</h3>
              <div className="flex items-center mb-2">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <span className="ml-2 text-muted-foreground">5.0</span>
              </div>
              <p className="text-muted-foreground mb-4">₹459 per kg</p>
              <Button className="w-full">Add to Cart</Button>
            </div>
          </div>
          <div className="bg-muted rounded-lg overflow-hidden shadow-lg">
            <img
              src="/placeholder.svg"
              alt="Organic Eggs from Nearby Farm"
              width={400}
              height={300}
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "400/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-bold mb-2">Organic Eggs from Nearby Farm</h3>
              <div className="flex items-center mb-2">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <span className="ml-2 text-muted-foreground">4.6</span>
              </div>
              <p className="text-muted-foreground mb-4">₹329 per dozen</p>
              <Button className="w-full">Add to Cart</Button>
            </div>
          </div>
          <div className="bg-muted rounded-lg overflow-hidden shadow-lg">
            <img
              src="/placeholder.svg"
              alt="Quinoa from Local Cooperative"
              width={400}
              height={300}
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "400/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-bold mb-2">Quinoa from Local Cooperative</h3>
              <div className="flex items-center mb-2">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <span className="ml-2 text-muted-foreground">3.9</span>
              </div>
              <p className="text-muted-foreground mb-4">₹259 per kg</p>
              <Button className="w-full">Add to Cart</Button>
            </div>
          </div>
          <div className="bg-muted rounded-lg overflow-hidden shadow-lg">
            <img
              src="/placeholder.svg"
              alt="Fresh Spinach from Farmer's Market"
              width={400}
              height={300}
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "400/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-bold mb-2">Fresh Spinach from Farmer's Market</h3>
              <div className="flex items-center mb-2">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <span className="ml-2 text-muted-foreground">4.6</span>
              </div>
              <p className="text-muted-foreground mb-4">₹159 per kg</p>
              <Button className="w-full">Add to Cart</Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
function LeafIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>
  )
}
